In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [4]:
## Define the vocabulary size
voc_size=10000

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7328, 8310, 7100, 783],
 [7328, 8310, 7100, 8043],
 [7328, 6821, 7100, 7638],
 [7361, 1765, 4305, 9784, 2432],
 [7361, 1765, 4305, 9784, 3648],
 [9878, 7328, 6138, 7100, 9656],
 [1093, 996, 2561, 9784]]

In [7]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7328 8310 7100  783]
 [   0    0    0    0 7328 8310 7100 8043]
 [   0    0    0    0 7328 6821 7100 7638]
 [   0    0    0 7361 1765 4305 9784 2432]
 [   0    0    0 7361 1765 4305 9784 3648]
 [   0    0    0 9878 7328 6138 7100 9656]
 [   0    0    0    0 1093  996 2561 9784]]


In [10]:
## feature representation
dim=10

In [11]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

C:\Users\ASUS\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 265ms/step


array([[[ 0.00074727,  0.0043314 , -0.04015682, -0.0254506 ,
         -0.02743812, -0.03568326, -0.01126094,  0.04132823,
          0.02498334,  0.01747559],
        [ 0.00074727,  0.0043314 , -0.04015682, -0.0254506 ,
         -0.02743812, -0.03568326, -0.01126094,  0.04132823,
          0.02498334,  0.01747559],
        [ 0.00074727,  0.0043314 , -0.04015682, -0.0254506 ,
         -0.02743812, -0.03568326, -0.01126094,  0.04132823,
          0.02498334,  0.01747559],
        [ 0.00074727,  0.0043314 , -0.04015682, -0.0254506 ,
         -0.02743812, -0.03568326, -0.01126094,  0.04132823,
          0.02498334,  0.01747559],
        [-0.04804179, -0.00140906,  0.00094056, -0.0160741 ,
         -0.00493084, -0.04326633, -0.01180457,  0.03570502,
          0.01095263, -0.04924336],
        [ 0.03865126,  0.04397989,  0.01565808,  0.01300783,
         -0.02511375, -0.04005891,  0.02419053, -0.02829783,
         -0.03718464,  0.0057217 ],
        [ 0.02306328,  0.04642856,  0.04313121,  0.0

In [14]:
embedded_docs[0]

array([   0,    0,    0,    0, 7328, 8310, 7100,  783])

In [19]:
model.predict(embedded_docs[0].reshape(1, -1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step


array([[[ 0.00074727,  0.0043314 , -0.04015682, -0.0254506 ,
         -0.02743812, -0.03568326, -0.01126094,  0.04132823,
          0.02498334,  0.01747559],
        [ 0.00074727,  0.0043314 , -0.04015682, -0.0254506 ,
         -0.02743812, -0.03568326, -0.01126094,  0.04132823,
          0.02498334,  0.01747559],
        [ 0.00074727,  0.0043314 , -0.04015682, -0.0254506 ,
         -0.02743812, -0.03568326, -0.01126094,  0.04132823,
          0.02498334,  0.01747559],
        [ 0.00074727,  0.0043314 , -0.04015682, -0.0254506 ,
         -0.02743812, -0.03568326, -0.01126094,  0.04132823,
          0.02498334,  0.01747559],
        [-0.04804179, -0.00140906,  0.00094056, -0.0160741 ,
         -0.00493084, -0.04326633, -0.01180457,  0.03570502,
          0.01095263, -0.04924336],
        [ 0.03865126,  0.04397989,  0.01565808,  0.01300783,
         -0.02511375, -0.04005891,  0.02419053, -0.02829783,
         -0.03718464,  0.0057217 ],
        [ 0.02306328,  0.04642856,  0.04313121,  0.0